#!/bin/bash
###This is the shell script to get the genome wide comparison between alloploidy cultivated peanut with two diploid wild peanut. 


/home/sunzq/prog/minimap2/minimap2 -t 20 -cx asm5 /share/10t/fangyj/gatk/Araip_v1.0_20140908.fa /share/10t/fangyj/bin/arahy.Tifrunner.gnm1.KYV3.main_genome.fna > arahyvsaraip.paf
/home/sunzq/prog/minimap2/minimap2 -t 20 -cx asm5 /share/10t/fangyj/gatk/Aradu_v1.0_20140908.fa /share/10t/fangyj/bin/arahy.Tifrunner.gnm1.KYV3.main_genome.fna > arahyvsaradu.paf

grep Arahy.01 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.01: "t"\nPerctange match: "ln/t}' 
grep Arahy.02 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.02: "t"\nPerctange match: "ln/t}' 
grep Arahy.03 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.03: "t"\nPerctange match: "ln/t}' 
grep Arahy.04 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.04: "t"\nPerctange match: "ln/t}' 
grep Arahy.05 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.05: "t"\nPerctange match: "ln/t}' 
grep Arahy.06 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.06: "t"\nPerctange match: "ln/t}' 
grep Arahy.07 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.07: "t"\nPerctange match: "ln/t}' 
grep Arahy.08 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.08: "t"\nPerctange match: "ln/t}' 
grep Arahy.09 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.09: "t"\nPerctange match: "ln/t}' 
grep Arahy.10 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.10: "t"\nPerctange match: "ln/t}' 
grep Arahy.11 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.11: "t"\nPerctange match: "ln/t}' 
grep Arahy.12 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.12: "t"\nPerctange match: "ln/t}' 
grep Arahy.13 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.13: "t"\nPerctange match: "ln/t}' 
grep Arahy.14 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.14: "t"\nPerctange match: "ln/t}' 
grep Arahy.15 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.15: "t"\nPerctange match: "ln/t}' 
grep Arahy.16 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.16: "t"\nPerctange match: "ln/t}' 
grep Arahy.17 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.17: "t"\nPerctange match: "ln/t}' 
grep Arahy.18 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.18: "t"\nPerctange match: "ln/t}' 
grep Arahy.19 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.19: "t"\nPerctange match: "ln/t}' 
grep Arahy.20 /share/10t/fangyj/gatk_3_3/araduvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.20: "t"\nPerctange match: "ln/t}' 
grep Arahy.01 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.01: "t"\nPerctange match: "ln/t}'
grep Arahy.02 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.02: "t"\nPerctange match: "ln/t}'
grep Arahy.03 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.03: "t"\nPerctange match: "ln/t}'
grep Arahy.04 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.04: "t"\nPerctange match: "ln/t}'
grep Arahy.05 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.05: "t"\nPerctange match: "ln/t}'
grep Arahy.06 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.06: "t"\nPerctange match: "ln/t}'
grep Arahy.07 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.07: "t"\nPerctange match: "ln/t}'
grep Arahy.08 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.08: "t"\nPerctange match: "ln/t}'
grep Arahy.09 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.09: "t"\nPerctange match: "ln/t}'
grep Arahy.10 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.10: "t"\nPerctange match: "ln/t}'
grep Arahy.11 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.11: "t"\nPerctange match: "ln/t}'
grep Arahy.12 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.12: "t"\nPerctange match: "ln/t}'
grep Arahy.13 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.13: "t"\nPerctange match: "ln/t}'
grep Arahy.14 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.14: "t"\nPerctange match: "ln/t}'
grep Arahy.15 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.15: "t"\nPerctange match: "ln/t}'
grep Arahy.16 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.16: "t"\nPerctange match: "ln/t}'
grep Arahy.17 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.17: "t"\nPerctange match: "ln/t}'
grep Arahy.18 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.18: "t"\nPerctange match: "ln/t}'
grep Arahy.19 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.19: "t"\nPerctange match: "ln/t}'
grep Arahy.20 /share/10t/fangyj/gatk_3_3/araipvsarahy.paf | awk -F"\t" '{ln+=$10;t=$2}END{print "Matched residue: "ln"\nTotal length of the chromosome Arahy.20: "t"\nPerctange match: "ln/t}'
